###############################################################################
############################ Skydive Analyzer #################################
###############################################################################

##################
# Image variables
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

image:
  repository: skydive/skydive
  tag: "0.26.0"
  secretName: ""
  imagePullPolicy: IfNotPresent

##################
# Resources
resources:
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 100m
    memory: 512Mi

##################
# Service variables
service:
  name: skydive
  port: 8082
  type: NodePort

##################
# ETCD variable
etcd:
  port: 12379
  expose: false

##################
# Analyzer
analyzer:
  topology:
    probes: ""
    fabric: "TOR1->*[Type=host]/eth0"

##################
# Persistence
persistence:
  ## Persistence disables by default
  enabled: false
  useDynamicProvisioning: false
  ## DataVolume for Persistence
  dataVolume:
    name: "datavolume"
    existingClaimName: ""
    storageClassName: ""
    size: 10Gi
  ## Storage for Persistence
  storage:
    flows:
      indicesToKeep: 10
      indexEntriesLimit: 10000
    topology:
      indicesToKeep: 10
      indexEntriesLimit: 10000
    elasticsearch:
      port: 9200
      host: 127.0.0.1

##################
# Elastic search image
elasticsearch:
  ## Enable elasticsearch deployment
  ## Persistence must be enabled
  deployment: false
  image:
    repository: "elastic/elasticsearch"
    tag: "7.5.1"
  env:
    - name: node.name
      value:  skydive-elastic-node
    - name: cluster.initial_master_nodes
      value:  skydive-elastic-node

##################
# Skydive UI image
ui:
  deployment: true
  image:
    repository: "skydive/skydive-ui"
    tag: "latest"
  port: 8080
  nodePort: 30083
##################
# env variables
env: []
