apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}-analyzer
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  selector:
    matchLabels:
      app: {{ template "fullname" . }}
  replicas: 1
  template:
    metadata:
      annotations:
        productName: {{ .Chart.Name }}
        productID: 8e6bdbcba44f46939c3d1c54447386b2
        productVersion: {{ .Chart.Version }}
      labels:
        app: {{ template "fullname" . }}
        chart: "{{ .Chart.Name }}"
        release: "{{ .Release.Name }}"
        heritage: "{{ .Release.Service }}"
        tier: analyzer
    spec:
      serviceAccountName: {{ template "fullname" . }}-service-account
      dnsPolicy: ClusterFirstWithHostNet
      affinity:
        {{- include "nodeaffinity" . | indent 6 }}
      {{- if .Values.image.secretName }}
      {{- if ne .Values.image.secretName ""}}
      imagePullSecrets:
      - name: {{ .Values.image.secretName }}
      {{- end }}
      {{- end }}      
      containers:
      - name: skydive-analyzer
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ default "" .Values.image.imagePullPolicy | quote }}
        terminationMessagePolicy: FallbackToLogsOnError
        args:
        - analyzer
        - --listen=0.0.0.0:{{ .Values.service.port }}
        ports:
        - containerPort: {{ .Values.service.port }}
        - containerPort: {{ .Values.service.port }}
          protocol: UDP
        - containerPort: {{ .Values.etcd.port }}
        readinessProbe:
          httpGet:
            port: {{ .Values.service.port }}
            path: /api/status
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: {{ .Values.service.port }}
            path: /api/status
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
        env:
        - name: SKYDIVE_UI
          value: '{"theme":"light","k8s_enabled":"true"}'
      {{- if .Values.persistence.enabled }}
        - name: SKYDIVE_ANALYZER_FLOW_BACKEND
          value: "elasticsearchflow"
        - name: SKYDIVE_ANALYZER_TOPOLOGY_BACKEND
          value: "elasticsearchtopology"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_DRIVER
          value: "elasticsearch"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_DRIVER
          value: "elasticsearch"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_HOST
          value: {{ .Values.persistence.storage.elasticsearch.host }}:{{ .Values.persistence.storage.elasticsearch.port }}/{{ .Values.persistence.storage.elasticsearch.query }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_INDICES_TO_KEEP
          value: {{ .Values.persistence.storage.flows.indicesToKeep | quote }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_INDEX_ENTRIES_LIMIT
          value: {{ .Values.persistence.storage.flows.indexEntriesLimit | quote }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_MAXCONNS
          value: "10"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_BULK_MAXDOCS
          value: "1000"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_BULK_MAXDELAY
          value: "10"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHFLOW_RETRY
          value: "5"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_HOST
          value: {{ .Values.persistence.storage.elasticsearch.host }}:{{ .Values.persistence.storage.elasticsearch.port }}/{{ .Values.persistence.storage.elasticsearch.query }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_INDICES_TO_KEEP
          value: {{ .Values.persistence.storage.topology.indicesToKeep | quote }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_INDEX_ENTRIES_LIMIT
          value: {{ .Values.persistence.storage.topology.indexEntriesLimit | quote }}
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_MAXCONNS
          value: "10"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_BULK_MAXDOCS
          value: "1000"
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_BULK_MAXDELAY
          value: "10"  
        - name: SKYDIVE_STORAGE_ELASTICSEARCHTOPOLOGY_RETRY
          value: "5"        
      {{- end }}
        - name: SKYDIVE_EMBEDDED
          value: "true"
        - name: SKYDIVE_FLOW_PROTOCOL
          value: "websocket"
        - name: SKYDIVE_ANALYZER_TOPOLOGY_FABRIC
          value: {{ .Values.analyzer.topology.fabric }}
      {{- if .Values.env }}
{{ toYaml .Values.env | indent 8 }}
      {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: ssl
          mountPath: /etc/ssl/certs
    {{- if and .Values.persistence.enabled .Values.elasticsearch.deployment }}
      - name: skydive-elasticsearch
        image: {{ .Values.elasticsearch.image.repository }}:{{ .Values.elasticsearch.image.tag }}
        ports:
        - containerPort: {{ .Values.persistence.storage.elasticsearch.port }}
        readinessProbe:
          httpGet:
            port: {{ .Values.persistence.storage.elasticsearch.port }}
            path: /
          initialDelaySeconds: 10
          periodSeconds: 10
        livenessProbe:
          httpGet:
            port: {{ .Values.persistence.storage.elasticsearch.port }}
            path: /
          initialDelaySeconds: 20
          periodSeconds: 10
          failureThreshold: 10
        env:
        - name: network.host
          value: "0.0.0.0"
        - name: xpack.security.enabled
          value: "false"
        {{- if .Values.elasticsearch.env }}
{{ toYaml .Values.elasticsearch.env | indent 8 }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}
        volumeMounts:
        - name: "{{ template "fullname" . }}-{{ .Values.persistence.dataVolume.name }}"
          mountPath: /usr/share/elasticsearch/data
    {{- end }}
    {{- if .Values.ui.deployment }}
      - name: skydive-ui
        image: {{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}
        ports:
           - containerPort: {{ .Values.ui.port }}
    {{- end }}
      volumes:
    {{- if and .Values.persistence.enabled .Values.elasticsearch.deployment }}
      - name: "{{ template "fullname" . }}-{{ .Values.persistence.dataVolume.name }}"
        persistentVolumeClaim:
        {{- if .Values.persistence.dataVolume.existingClaimName }}
          claimName: {{ .Values.persistence.dataVolume.existingClaimName }}
        {{- else }}
          claimName: {{ template "fullname" . }}-{{ .Values.persistence.dataVolume.name }}
        {{- end }}
    {{- end }}
      - name: ssl
        hostPath:
          path: /etc/ssl/certs

