apiVersion: v1
kind: Service
metadata:
  name: "{{ template "fullname" . }}-service"
  labels:
    app: {{ template "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"

spec:
  type: {{ .Values.service.type }}
  ports:
  - port: {{ .Values.service.port }}
    name: {{ .Values.service.name }}
    nodePort: {{ .Values.service.nodePort }}
  {{- if .Values.etcd.expose }}
  - port: {{ .Values.etcd.port }}
    name: "{{ template "fullname" . }}-etcd"
    nodePort: {{ .Values.etcd.nodePort }}
  {{- end }}
  selector:
    app: {{ template "fullname" . }}
    tier: analyzer

