###############################################################################
############################ Skydive ##########################################
###############################################################################

##################
# Image variables
arch:
  amd64: "2 - No preference"
  ppc64le: "2 - No preference"
  s390x: "2 - No preference"

image:
  repository: skydive/skydive
  tag: "0.26.0"
  secretName: ""
  imagePullPolicy: IfNotPresent

##################
# Resources
resources:
  limits:
    cpu: 2000m
    memory: 8192Mi
  requests:
    cpu: 100m
    memory: 512Mi

##################
# Service variables
service:
  port: 8082

##################
# Analyzer
agent:
  topology:
    probes: "ovsdb docker runc"

## env variables
env: []